#!/bin/bash

# Двухсторонняя синхронизация
# Использование:
# 2sync src dest

src=$1
dest=$2
opt=$3

rsync -r -t -v $opt --progress -s --omit-dir-times $src $dest
rsync -r -t -v $opt --progress -s --omit-dir-times $dest $src


