#!/bin/bash
cd /home
sudo tar cvpzf home_backup_$(date +%yy%mm%dd-%Hh%Mm%Ss).tgz \
--exclude=home_backup*.tgz \
--exclude=.thumbnails \
--exclude=.mozilla/firefox/*.default/Cache \
--exclude=.googleearth/Cache \
.
