#!/bin/bash

maxFilesCount=3
backup_dir=""

# Выясняем, какие старые архивы нам нужно удалить
files=`find ${backup_dir}/*sysbackup_*|sort`
delFiles=`./GetDelFileList $maxFilesCount "${files}"`

cd /
sudo tar cvpzf "${backup_dir}/$(hostname)_sysbackup_$(date +%yy%mm%dd-%Hh%Mm%Ss).tgz" \
--exclude=/proc \
--exclude=/lost+found \
--exclude=/*sysbackup*.tgz \
--exclude=/mnt \
--exclude=/sys \
--exclude=/home \
--exclude=/media \
--exclude=/var/cache \
--exclude=/var/tmp \
--exclude=/usr/share/games \
--exclude=/tmp \
/

# Удаляем старые архивы
for i in $delFiles
do
	sudo rm $i
done
