#!/bin/bash

# Делает бэкап папки /home
# Использование:
# ./MakeHomeBackup backup_dir

backup_dir=$1
if [ "$backup_dir" == "" ]; then
   backup_dir="/home"
fi

maxFilesCount=3
# Выясняем, какие старые архивы нам нужно удалить
files=`find ${backup_dir}/*home_backup_*|sort`
delFiles=`./GetDelFileList $maxFilesCount "${files}"`

# Делаем бекап
cd /home
sudo tar cvpzf "${backup_dir}/$(hostname)_home_backup_$(date +%yy%mm%dd-%Hh%Mm%Ss).tgz" \
--exclude=*home_backup*.tgz \
--exclude=.thumbnails \
--exclude=.mozilla/firefox/*.*/storage \
--exclude=*/.cache/* \
--exclude=*/Загрузки/* \
--exclude=*/Backup/* \
--exclude=*/Музыка/* \
--exclude=.cache \
--exclude=/.config/chromium/*/CacheStorage \
--exclude=*/.config/skypeforlinux/Cache \
--exclude=.local \
--exclude=.var/app/app.organicmaps.desktop/data \
--exclude=media \
--exclude=.steam \
--exclude=.smartgit/updates \
--exclude=.wine*/*/windows/ \
--exclude=.googleearth \
--exclude=*/.Genymobile \
--exclude=*/3D_Model/assets \
--exclude=private \
--exclude=MyProgs \
--exclude=go/pkg \
--exclude=.apt \
--exclude=.npm \
--exclude=.gradle \
.

# Удаляем старые архивы
for i in $delFiles
do
	sudo rm $i
done
