#!/bin/bash

# Выясняем, какие старые архивы нам нужно удалить
maxFilesCount=3
files=`find /sysbackup_*|sort`
delFiles=`./GetDelFileList $maxFilesCount "${files}"`

cd /
sudo tar cvpzf sysbackup_$(date +%yy%mm%dd-%Hh%Mm%Ss).tgz \
--exclude=/proc \
--exclude=/lost+found \
--exclude=/sysbackup*.tgz \
--exclude=/mnt \
--exclude=/sys \
--exclude=/home \
--exclude=/media \
--exclude=/usr/share/games \
--exclude=/tmp \
/

# Удаляем старые архивы
for i in $delFiles
do
	sudo rm $i
done
