#!/bin/bash

source "${alias_dir}/crontab"
source "${alias_dir}/install"
source "${alias_dir}/pdf"
source "${alias_dir}/hdd"
source "${alias_dir}/openwrt"
source "${alias_dir}/utils"
source "${alias_dir}/video"
source "${alias_dir}/image"
source "${alias_dir}/ssh"
source "${alias_dir}/download"
source "${alias_dir}/lang"
source "${alias_dir}/parse_arg_lib"
source "${alias_dir}/img_and_wav2video"
source "${alias_dir}/nmap"
source "${alias_dir}/backup"
source "${alias_dir}/sync"


