#!/bin/bash

# Copyright 2025 by Alexei Bezborodov <AlexeiBv+linux_script@narod.ru> 
# License: Public domain: http://unlicense.org/ 
# Общественное достояние 

[ "${alias_dir}" = "" ] && alias_dir=$(pwd)
source "${alias_dir}/common"

img_all_to_djvu()
{
    [ ${in_files_pattern} == '' ] && printf "Объедидение файлов в djvu\nУкажите входной шаблон. Например '*.jpg'\n" && return
    in_files_pattern=$1
    for i in ${in_files_pattern}; do bmptopnm $i > pnm/$i.pnm; done
    for i in *; do c44 -dpi 300 -slice 60+7+7 $i $i.djvu; done
    djvm -c new.djvu *.djvu
}
mkalias_with_prefix 'img_all_to_djvu'

img_resize()
{
    eval $(mkvar 'search_template|$1|*.JPG|Изменение размера и удаление exif\nУкажите входной шаблон файлов и ширину. Например: \"*.JPG\" 1536\nВыбран шаблон по умолчанию \"*.JPG\"\n')
    eval $(mkvar 'image_width|$2|1536')
    eval $(mkvar 'image_params|$3|')

    resize_img_dir="resize_img"
    echo "image_width = ${image_width}"
    echo "search_template = ${search_template}"

    mkdir ${resize_img_dir}
    for entry in $search_template;
    do
        echo "entry= ${entry}"
        echo "image_width = ${image_width}"
        convert "${entry}" -resize ${image_width} ${image_params} "${resize_img_dir}/${entry}"
    done
}
mkalias_with_prefix 'img_resize'

img_resize_and_del_exif()
{
    img_resize "$1" $2 -strip
}
mkalias_with_prefix 'img_resize_and_del_exif'


