#!/bin/bash

img_all_to_djvu()
{
    [ ${in_files_pattern} == '' ] && printf "Объедидение файлов в djvu\nУкажите входной шаблон. Например '*.jpg'\n" && return
    in_files_pattern=$1
    for i in ${in_files_pattern}; do bmptopnm $i > pnm/$i.pnm; done
    for i in *; do c44 -dpi 300 -slice 60+7+7 $i $i.djvu; done
    djvm -c new.djvu *.djvu
}
mkalias_with_prefix 'img_all_to_djvu'

img_resize()
{
    search_template=$1
    [ "${search_template}" == "" ] && printf "Изменение размера и удаление exif\nУкажите входной шаблон файлов и ширину. Например: \"*.JPG\" 1536\nВыбран шаблон по умолчанию \"*.JPG\"\n" && search_template="*.JPG" && ask_continue && return

    image_width=$2
    echo "${image_width}"
    [ "${image_width}" = "" ] && image_width="1536" && printf "Выбрана ширина '${image_width}'\n"

    image_params=$3

    resize_img_dir="resize_img"
    mkdir ${resize_img_dir}
    for entry in $search_template;
    do
        echo "${entry}"
        convert "${entry}" -resize ${image_width} ${image_params} "${resize_img_dir}/${entry}"
    done
}
mkalias_with_prefix 'img_resize'

img_resize_and_del_exif()
{
    img_resize $1 $2 -strip
}
mkalias_with_prefix 'img_resize_and_del_exif'


