#!/bin/bash

ssh_del_known_host()
{
    in_host_pattern=$1
    [ "${in_host_pattern}" = "" ] && printf "Укажите шаблон адреса, например '192.168.1.'\n" && return
    eval "sudo cp -u ~/.ssh/known_hosts ~/.ssh/known_hosts.backup && cat ~/.ssh/known_hosts.backup | grep -v ${in_host_pattern} > ~/.ssh/known_hosts"
}
mkalias_with_prefix 'ssh_del_known_host'

ssh_for_openwpt_10.3_kamikadze()
{
    in_host_pattern=$1
    ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c 3des-cbc ${in_host_pattern}

}
mkalias_with_prefix 'ssh_for_openwpt_10.3_kamikadze'
