#!/bin/sh
# Общественное достояние, 2024, Алексей Безбородов (Alexei Bezborodov) <AlexeiBv+mirocod_txt2mp3@narod.ru> 

# Тест всех голосов

in_file=$1

declare -a speaker_arr=("oksana" "jane" "omazh" "zahar" "ermil" "silaerkan" "erkanyavas" "alyss"  "nick")
declare -a emotion_arr=("neutral" "good" "evil")

for s in "${speaker_arr[@]}"
do
    for e in "${emotion_arr[@]}"
    do
        echo "speaker ${s} emotion ${e}"
        echo "~/txt2mp3_by_yatts -i \"${in_file}\" -o \"${in_file}_${s}_${e}.mp3\" -e \"${e}\" -s \"${s}\""
        ~/txt2mp3_by_yatts -i "${in_file}" -o "${in_file}_${s}_${e}.mp3" -e "${e}" -s "${s}"
    done
done

